// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDFVqpf70xPsawGd-xCfczaI24TfyL_FH8",
    authDomain: "cpad-89722.firebaseapp.com",
    projectId: "cpad-89722",
    storageBucket: "cpad-89722.appspot.com",
    messagingSenderId: "132471750803",
    appId: "1:132471750803:web:942f4b3aebaeb451fecd66",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy0t5fjWsC0jBtdFRUsCILgT99edixrjs',
    appId: '1:132471750803:android:51c1f89b2c8b6cb2fecd66',
    messagingSenderId: '132471750803',
    projectId: 'cpad-89722',
    storageBucket: 'cpad-89722.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy0t5fjWsC0jBtdFRUsCILgT99edixrjs',
    appId: '1:132471750803:ios:fb47c2f360d27735fecd66',
    messagingSenderId: '132471750803',
    projectId: 'cpad-89722',
    storageBucket: 'cpad-89722.appspot.com',
    iosBundleId: 'com.example.cpad',
  );

}
